### PR TITLE
Fixes: SetCallerInfo, panic/fail in Log, concurrent=false, Fail & SetCallerInfo unit tests

### LINKED ISSUE #11: slf.Log(slf.LevelFatal does not lead to os.Exit and slf.Log(slf.LevelPanic does not panic

### LINKED ISSUE #12: SetCallerInfo is not functioning as intended
I have just added the tests missing from the original PR. 

The code was copied from SetLevel, but for SetLevel it is sufficient to alter the root logger in each context, SetCallerInfo needs to get to each instance derived from that root and these are not tracked centrally. A solution might be to check the root logger when outputting the caller info, but then which one should take the precedence, the one from the root or from the instance.

Working on a fix now.

### PR DESCRIPTION
**Pull request by osklyar**
@veqryn FYI

Fixed SetCallerInfo, fixed panic/fail in Log, changed concurrent to false and boosted coverage back to 100%

fixes #11 
fixed #12 
fixes #8

### CODE REVIEW

File: logger.go [hunk 1]
```diff
@@ -11,7 +11,6 @@ import (
 	"path"
 	"runtime"
 	"time"
-	"os"
```
Comment (osklyar) [inline logger.go]: @veqryn please run make all before commit as it performs formatting (relevant here), checks vetting and runs tests

**Comment by osklyar** [comment]
fix #11

File: logger.go [hunk 2]
```diff
@@ -30,6 +29,11 @@ const (
 var (
 	noop  = &slf.Noop{}
 	epoch = time.Time{}
+
+	// ExitProcessor is executed on Log(LevelFatal) to terminate the application.
+	ExitProcessor = func(message string) {
+		stdlog.Fatal(message)
```
Comment (veqryn) [inline logger.go]: Wouldn't this cause the log to output the message twice, since stdlog goes to stdout/stderr?

Comment (osklyar) [inline logger.go]: Provided the text logger is used and bound to stderr or stdout it would (partially, here without structured data). Same with panic, it also gets the message. I sort of feel those exceptions help rather than harm. What do you think?

Comment (veqryn) [inline logger.go]: So on all my systems, all my logging goes to stdout, which is then picked up by something else, such as logstash, scalyr, docker, supervisor, etc.  I also output exclusively in json, that way when it ends up aggregated in somewhere I can perform queries and metrics easily.  
So in this case, I'd get the message twice, once in json, once just as a text line. Non-json tends to make my log-parsers unhappy, so I'd rather not have the message twice.  
(On the note about panic's, if I could get those in json form I would; but since I can't I've created custom log-parsing rules to look for panics.)

Comment (osklyar) [inline logger.go]: Fair enough, I'll take it out

Comment (osklyar) [inline logger.go]: Will replce with os.Exit I meant to say
